"""add module_validation_logs table

Revision ID: 6ca4c9427802
Revises: b247dbb084dc
Create Date: 2025-05-24 03:08:19.253053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca4c9427802'
down_revision: Union[str, None] = 'b247dbb084dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'module_validation_logs',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
    )
    # op.alter_column('error_log', 'code',
    #            existing_type=sa.VARCHAR(length=64),
    #            nullable=False)
    # op.alter_column('error_log', 'message',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.alter_column('modules', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.Integer(),
    #            nullable=True,
    #            existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_validation_logs')
    # op.alter_column('modules', 'is_active',
    #            existing_type=sa.Integer(),
    #            type_=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('1'))
    # op.alter_column('error_log', 'message',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('error_log', 'code',
    #            existing_type=sa.VARCHAR(length=64),
    #            nullable=True)
    # ### end Alembic commands ###
