"""add module validation log table

Revision ID: b19f019154f8
Revises: b7e1b5fbbf80
Create Date: 2025-05-23 14:45:09.452369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19f019154f8'
down_revision: Union[str, None] = 'b7e1b5fbbf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'module_history',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('module_id', sa.Integer(), sa.ForeignKey('modules.id'), nullable=False),
        sa.Column('version_id', sa.Integer(), sa.ForeignKey('versions.id'), nullable=False),
        sa.Column('action', sa.String(32), nullable=False),  # rollback, activate, deactivate
        sa.Column('operator', sa.String(64), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    )
    op.add_column('modules', sa.Column('is_active', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_history')
    op.drop_column('modules', 'is_active')
    # ### end Alembic commands ###
