"""create user table

Revision ID: d59e638a2862
Revises: 
Create Date: 2025-05-22 19:54:23.242922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, DateTime
import datetime
import hashlib


# revision identifiers, used by Alembic.
revision: str = 'd59e638a2862'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    user_table = table('users',
        column('id', Integer),
        column('username', String),
        column('email', String),
        column('hashed_password', String),
        column('created_at', DateTime)
    )
    # 'admin'의 sha256 해시
    admin_password = hashlib.sha256('admin'.encode('utf-8')).hexdigest()
    op.bulk_insert(
        user_table,
        [
            {
                "id": 1,
                "username": "admin",
                "email": "admin@hatiolab.com",
                "hashed_password": admin_password,
                "created_at": datetime.datetime.utcnow()
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
