# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import executor_pb2 as executor__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/operato.runner.Executor/Execute',
                request_serializer=executor__pb2.ExecRequest.SerializeToString,
                response_deserializer=executor__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ListModules = channel.unary_unary(
                '/operato.runner.Executor/ListModules',
                request_serializer=executor__pb2.ListModulesRequest.SerializeToString,
                response_deserializer=executor__pb2.ListModulesResponse.FromString,
                _registered_method=True)
        self.GetModule = channel.unary_unary(
                '/operato.runner.Executor/GetModule',
                request_serializer=executor__pb2.GetModuleRequest.SerializeToString,
                response_deserializer=executor__pb2.ModuleInfo.FromString,
                _registered_method=True)
        self.RegisterModule = channel.unary_unary(
                '/operato.runner.Executor/RegisterModule',
                request_serializer=executor__pb2.RegisterModuleRequest.SerializeToString,
                response_deserializer=executor__pb2.ModuleInfo.FromString,
                _registered_method=True)
        self.DeleteModule = channel.unary_unary(
                '/operato.runner.Executor/DeleteModule',
                request_serializer=executor__pb2.DeleteModuleRequest.SerializeToString,
                response_deserializer=executor__pb2.DeleteModuleResponse.FromString,
                _registered_method=True)


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=executor__pb2.ExecRequest.FromString,
                    response_serializer=executor__pb2.ExecResponse.SerializeToString,
            ),
            'ListModules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModules,
                    request_deserializer=executor__pb2.ListModulesRequest.FromString,
                    response_serializer=executor__pb2.ListModulesResponse.SerializeToString,
            ),
            'GetModule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModule,
                    request_deserializer=executor__pb2.GetModuleRequest.FromString,
                    response_serializer=executor__pb2.ModuleInfo.SerializeToString,
            ),
            'RegisterModule': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModule,
                    request_deserializer=executor__pb2.RegisterModuleRequest.FromString,
                    response_serializer=executor__pb2.ModuleInfo.SerializeToString,
            ),
            'DeleteModule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModule,
                    request_deserializer=executor__pb2.DeleteModuleRequest.FromString,
                    response_serializer=executor__pb2.DeleteModuleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operato.runner.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('operato.runner.Executor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operato.runner.Executor/Execute',
            executor__pb2.ExecRequest.SerializeToString,
            executor__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operato.runner.Executor/ListModules',
            executor__pb2.ListModulesRequest.SerializeToString,
            executor__pb2.ListModulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operato.runner.Executor/GetModule',
            executor__pb2.GetModuleRequest.SerializeToString,
            executor__pb2.ModuleInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operato.runner.Executor/RegisterModule',
            executor__pb2.RegisterModuleRequest.SerializeToString,
            executor__pb2.ModuleInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operato.runner.Executor/DeleteModule',
            executor__pb2.DeleteModuleRequest.SerializeToString,
            executor__pb2.DeleteModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
