# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x0eoperato.runner\"1\n\x0b\x45xecRequest\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x12\n\njson_input\x18\x02 \x01(\t\"c\n\x0c\x45xecResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x11\n\texit_code\x18\x02 \x01(\x05\x12\x0e\n\x06stderr\x18\x03 \x01(\t\x12\x0e\n\x06stdout\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x05 \x01(\x01\"\x14\n\x12ListModulesRequest\"B\n\x13ListModulesResponse\x12+\n\x07modules\x18\x01 \x03(\x0b\x32\x1a.operato.runner.ModuleInfo\" \n\x10GetModuleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"Z\n\nModuleInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x65nv\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\"m\n\x15RegisterModuleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x65nv\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\"#\n\x13\x44\x65leteModuleRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteModuleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa3\x03\n\x08\x45xecutor\x12\x44\n\x07\x45xecute\x12\x1b.operato.runner.ExecRequest\x1a\x1c.operato.runner.ExecResponse\x12V\n\x0bListModules\x12\".operato.runner.ListModulesRequest\x1a#.operato.runner.ListModulesResponse\x12I\n\tGetModule\x12 .operato.runner.GetModuleRequest\x1a\x1a.operato.runner.ModuleInfo\x12S\n\x0eRegisterModule\x12%.operato.runner.RegisterModuleRequest\x1a\x1a.operato.runner.ModuleInfo\x12Y\n\x0c\x44\x65leteModule\x12#.operato.runner.DeleteModuleRequest\x1a$.operato.runner.DeleteModuleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECREQUEST']._serialized_start=34
  _globals['_EXECREQUEST']._serialized_end=83
  _globals['_EXECRESPONSE']._serialized_start=85
  _globals['_EXECRESPONSE']._serialized_end=184
  _globals['_LISTMODULESREQUEST']._serialized_start=186
  _globals['_LISTMODULESREQUEST']._serialized_end=206
  _globals['_LISTMODULESRESPONSE']._serialized_start=208
  _globals['_LISTMODULESRESPONSE']._serialized_end=274
  _globals['_GETMODULEREQUEST']._serialized_start=276
  _globals['_GETMODULEREQUEST']._serialized_end=308
  _globals['_MODULEINFO']._serialized_start=310
  _globals['_MODULEINFO']._serialized_end=400
  _globals['_REGISTERMODULEREQUEST']._serialized_start=402
  _globals['_REGISTERMODULEREQUEST']._serialized_end=511
  _globals['_DELETEMODULEREQUEST']._serialized_start=513
  _globals['_DELETEMODULEREQUEST']._serialized_end=548
  _globals['_DELETEMODULERESPONSE']._serialized_start=550
  _globals['_DELETEMODULERESPONSE']._serialized_end=589
  _globals['_EXECUTOR']._serialized_start=592
  _globals['_EXECUTOR']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
