apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operato-runner.fullname" . }}-config
  labels:
    {{- include "operato-runner.labels" . | nindent 4 }}
data:
  modules.yaml: |
    # Default modules configuration
    modules:
      - name: hello-world
        env: inline
        code: |
          def handler(input):
              return {"message": f"Hello, {input.get('name', 'World')}!"}
        version: "0.1.0"
        tags:
          - example
          - greeting
