apiVersion: v1
kind: Secret
metadata:
  name: { { include "operato-runner.fullname" . } }
  labels: { { - include "operato-runner.labels" . | nindent 4 } }
type: Opaque
data:
  jwt-secret: { { .Values.config.jwtSecret | b64enc } }
