apiVersion: v1
kind: Service
metadata:
  name: { { include "operato-runner.fullname" . } }
  labels: { { - include "operato-runner.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.restPort } }
      targetPort: rest
      protocol: TCP
      name: rest
    - port: { { .Values.service.grpcPort } }
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector: { { - include "operato-runner.selectorLabels" . | nindent 4 } }
